language: android

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - /usr/local/android-sdk

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-android-24

before_install:
- echo y | android update sdk -a --no-ui --filter android-24
- echo y | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-24
- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}'
- echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
- emulator -avd test -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
- adb wait-for-device get-serialno
- chmod +x gradlew